swagger-api:
  version: "1.0"
logging:
  level:
    org.springframework: info
    com.edu.ulab.app: debug
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:userbook
    username: test
    password: test
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
server:
  port: 8091
  servlet:
    context-path: /app
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info